### PR TITLE
Switch to docker dependabot

### PR DESCRIPTION
**Pull request by timja**

### CODE REVIEW

**Comment by dduportal** [comment]
Hello @timja ! What is the goal of switching to dependabot?

(I'm asking because @lemeurherve were planning to switch this repo to full updatecli to stay coherent with the others, and get rid of the GH action + `uc` setup here)

**Comment by timja** [comment]
> Hello @timja ! What is the goal of switching to dependabot?
> 
> (I'm asking because @lemeurherve were planning to switch this repo to full updatecli to stay coherent with the others, and get rid of the GH action + `uc` setup here)

Far simpler to understand for contributors, than update cli, and zero config required.

Dependabot generally just works out of the box by enabling it.

Imo (and I'm sure we discussed this before) where we can use it we should use it, and it supports docker...

**Comment by dduportal** [comment]
> > Hello @timja ! What is the goal of switching to dependabot?
> > (I'm asking because @lemeurherve were planning to switch this repo to full updatecli to stay coherent with the others, and get rid of the GH action + `uc` setup here)
> 
> Far simpler to understand for contributors, than update cli, and zero config required.
> 
> Dependabot generally just works out of the box by enabling it.
> 
> Imo (and I'm sure we discussed this before) where we can use it we should use it, and it supports docker...

I agree for building stuff that are usable by end user, or "high rate" contribution project. But this repo (and its twin jenkins-infra/docker-jenkins-lts) are only built for one purpose: our own usage for infra.ci and release.ci.

I agree for dependanbot for upgrading the FROM. But dependanbot deoesn't manage plugins: it's the reason why we wanted to "tight" into update cli the combination of core + plugins at the same time (because even today, with the current `uc` it's already the case).

**Comment by timja** [comment]
> I agree for dependanbot for upgrading the FROM

Which is what this PR does?

> But dependanbot deoesn't manage plugins

Renovate does this, but unfortunately it doesn't work with JEP-229, see https://github.com/jenkins-infra/jenkins.io/issues/4783

**Comment by dduportal** [comment]
Closing as no immediate actions are planned.

**Pull request closed without merging**
