### PR TITLE
[JENKINS-49707] Pick up proposed final changes

### PR DESCRIPTION
**Pull request by jglick**
Following up #512 and countermanding #532 if you are willing to run these prior to release @dduportal. Picks up https://github.com/jenkinsci/workflow-api-plugin/pull/256 + https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/180. Briefly, this would make it possible for `retry` blocks to work even if the agent outage was detected during a controller restart, as might occur for example during cluster updates (draining node pools, that sort of thing).

### CODE REVIEW

**Review by smerle33 — APPROVED** [review]
🚀

**Comment by jglick** [comment]
Is this live? Any issues noticed so far?

**Comment by jglick** [comment]
No one screaming bloody regression so far, so I guess it is OK.

**Comment by dduportal** [comment]
Hey sorry @jglick for the delayed answer. So yes it is live in infra.ci.jenkins.io since ~7 days and no issues.

We can proceed to release, unless you want also a test on ci.jenkins.io itself?

**Comment by jglick** [comment]
Thanks. I am proceeding to release.

**Pull request merged**
