### PR TITLE
feat: disable weather icon

### PR DESCRIPTION
**Pull request by dduportal**
The CloudBees Advisory for infra.ci instance complains weekly that the weather icon are having slow requests.

It doesn't seem that there is a way to disable the weather icon with JCasc, neither with the Jenkins Helm chart.

Since https://groups.google.com/g/jenkins-infra/c/jDwhKfh2ejI is going in the direction of using opentelemetry, and that we already colelct metrics in both our prometheus and datadog platforms, then the weather system has a low value for our instances, while slowing down performances.

As such, this PR applies https://support.cloudbees.com/hc/en-us/articles/216973327 in the form of a Groovy script in this image.

Script output outputs the following when run on infra.ci.jenkins.io's console in dry-run mode:

```text
Would remove WorstChildHealthMetric from charts
Would remove WorstChildHealthMetric from custom-distribution-service
Would remove WorstChildHealthMetric from Docker Builds
Would remove WorstChildHealthMetric from incrementals-publisher
Would remove WorstChildHealthMetric from jenkins-wiki-exporter
Would remove WorstChildHealthMetric from k8smgmt
Would remove WorstChildHealthMetric from plugin-site
Would remove WorstChildHealthMetric from Terraform Jobs
Would remove WorstChildHealthMetric from aws
Would remove WorstChildHealthMetric from datadog
Would remove WorstChildHealthMetric from docker-404
Would remove WorstChildHealthMetric from docker-aws
Would remove WorstChildHealthMetric from docker-builder
Would remove WorstChildHealthMetric from docker-crond
Would remove WorstChildHealthMetric from docker-datadog
Would remove WorstChildHealthMetric from docker-helmfile
Would remove WorstChildHealthMetric from docker-inbound-agents
Would remove WorstChildHealthMetric from docker-jenkins-lts
Would remove WorstChildHealthMetric from docker-jenkins-weekly
Would remove WorstChildHealthMetric from docker-mirrorbits
Would remove WorstChildHealthMetric from docker-packer
Would remove WorstChildHealthMetric from docker-rsyncd
Would remove WorstChildHealthMetric from docker-terraform
Would remove WorstChildHealthMetric from jenkins.io
```

### CODE REVIEW

**Review by timja — COMMENTED** [review]
isn't this a jobdsl thing and not a jcasc thing? there's also https://github.com/jenkinsci/configuration-as-code-groovy-plugin if there's no job dsl way for this

**Comment by timja** [comment]
Reading the linked page don't we just need to run that script once in the script console? They won't be added for new ones?

**Comment by dduportal** [comment]
Hello @timja , thanks for the feedback, I think you make valid point and I'm gonna close the PR to switch to a JCasc setup (see below).

> isn't this a jobdsl thing and not a jcasc thing? 

With JobDSL, I only found the method `weather()` which would forcibly enable the weather column, but nothing around disabling. I'm sorry, I should have mentioned this in the PR description.

> Reading the linked page don't we just need to run that script once in the script console? They won't be added for new ones?

That's what I thought, but by trying locally with a copy of infra.ci, adding a new GH scanning folder enable the weather on this new folder: it seems like that only the "pure folders" are disabling the weather column (there are no mention of the weather in https://github.com/jenkinsci/github-branch-source-plugin/releases, I feel like the PR in https://github.com/jenkinsci/cloudbees-folder-plugin/releases/tag/cloudbees-folder-6.15 has not been transplanted in GitHub Branch Source plugin but I'm not really sure how it works under the hood, haven't read the code).

> there's also https://github.com/jenkinsci/configuration-as-code-groovy-plugin if there's no job dsl way for this

Oh yes, I was not aware of this plugin, I love this! In this case, I'm gonna:
- Open a new PR in the repo. here to add this plugin
- Open a PR in charts to ensure that we have the groovy script as a JCasc element once plugin is available

**Comment by timja** [comment]
cc @fbelzunc and @bitwiseman as an FYI

**Comment by fbelzunc** [comment]
I thought [this PR](https://github.com/jenkinsci/cloudbees-folder-plugin/pull/153) made the Health Metrics not to be there by default + you can now customize what you would by default from Manage Jenkins -> Configure System. IIRC this can also be customized with JCasC ro put it back by defaul with

```
unclassified:
  defaultFolderConfiguration:
    healthMetrics:
    - "projectEnabledHealthMetric"
```

**Comment by timja** [comment]
this is what we currently have set:

image

**Comment by dduportal** [comment]
I'm confused: what are the steps to, when using a full GitOps setup, to ensure that no weather icon is set up?

**Comment by dduportal** [comment]
(side question: when I create a GitHub Organization Scanning or a MultiBranch, does it use the same things as a "Folder" - e.g. does it extends Folder, or is it completely different?)

**Pull request closed without merging**
